version: 2.1
orbs:
  node: circleci/node@5.1.0
jobs:
  test-and-build:
    docker:
      - image: cimg/node:18.16.1
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Unit and API Tests, lint, Prettier check, Spellcheck
          command: npm t
      - run:
          name: Build (Client, Server, and Content)
          command: npm run build

workflows:
  test:
    when:
      condition:
        equal: [main, << pipeline.git.branch >>]
    jobs:
      - test-and-build
