version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.5
  node: circleci/node@5.1.0
jobs:
  read-wordle-page:
    docker:
      - image: cimg/node:18.16.1-browsers
    steps:
      - browser-tools/install-browser-tools
      - checkout
      - node/install-packages
      - run: npm run test:browser -- --spec test-browser/specs/ci.browser.test.ts -c

workflows:
  test:
    jobs:
      - read-wordle-page
