version: 2.1
orbs:
  node: circleci/node@4.3.0
  heroku: circleci/heroku@1.2.6
workflows:
  heroku-deploy:
    jobs:
      - node/test:
          version: "16.16.0"
      - heroku/deploy-via-git:
          filters:
            branches:
              only:
                - main
          force: true
          requires:
            - node/test



